version: "3.9"

networks:
  hospital-network:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: hospital-user-credentials
    restart: always
    environment:
      MONGO_INITDB_DATABASE: UserCredentials
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27018:27017"
    volumes:
      - hospital-user-credentials_container:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      hospital-network:
        aliases:
          - mongo
  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/UserCredentials?useNewUrlParser=true&useUnifiedTopology=true
    networks:
      hospital-network:
volumes:
  hospital-user-credentials_container:
