name: Build Docker Container for Hospital SDK & Push to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Get previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
      - name: Get next minor version
        id: semver
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build web container image for hospital-sdk
        run: |
          cd hospital-sdk
          docker build -t sms7/hospital-sdk:latest -t sms7/hospital-sdk:${{ steps.semver.outputs.patch }} .
      - name: Push container latest version
        run: docker push sms7/hospital-sdk:latest
      - name: Push container with version
        run: docker push sms7/hospital-sdk:${{ steps.semver.outputs.patch }}
