name: Generate Tags For Docker image version..
on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: "Get next minor version"
        id: semver
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Create  and push tag
        run: |
          git tag ${{ steps.semver.outputs.patch }}
          git push --tags
      - name: "Create new milestone"
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ steps.semver.outputs.patch }}
        env:
          GITHUB_TOKEN: "${{ secrets.SECRET_TOKEN }}"
